### ISSUE TITLE
かずき👈アンケート回答画面の人数が合っていない

### ISSUE THREAD

**Issue by ittyi** [Kazuki0320/GolfApp#51]
3人になっている原因
- コード見たら、謎のマジックナンバー＋コードがある

_Originally posted by @Kazuki0320 in https://github.com/Kazuki0320/GolfApp/issues/47#issuecomment-1400582517_

**Comment by Kazuki0320** [comment]
### 内容
アンケート回答画面の人数が合っていない。
→この実装については、アンケート回答画面には名前の表示をする

### リスト
- [ ] アンケート回答画面の表示を名前の表示に変更する。

**Comment by Kazuki0320** [comment]
LGTM
